#################################
#
# Backend
#
#################################

# Backend to use: "xrender" or "glx".
# GLX backend is typically much faster but depends on a sane driver.

backend = "glx";


#################################
#
# GLX backend
#
#################################

glx-no-stencil = true;
glx-copy-from-front = false;
glx-no-rebind-pixmap = true;
use-damage = true;


#################################
#
# Shadows
#
#################################

shadow = true;
shadow-radius = 30;
shadow-offset-x = 0;
shadow-offset-y = 0;
shadow-opacity = .5;
shadow-exclude = [
  "_GTK_FRAME_EXTENTS@:c",
  "name = 'Notification'",
  "name ?= 'xfwm4' && argb",
  "class_g = 'conky'",
  "class_g ?= 'Notify-osd'",
  "class_g ?= 'Xfce4-notifyd'",
  "name ?= 'Thunderbird' && (window_type = 'utility' || window_type = 'popup_menu')",
  "class_g ?= 'appy-gtk' && (window_type = 'menu')",
  "class_g ?= 'Thunderbird' && class_i = 'Popup' && argb",
  "class_g = 'firefox' && (window_type = 'utility' || window_type = 'popup_menu') && argb",
  "class_g = 'Firefox' && (window_type = 'utility' || window_type = 'popup_menu') && argb",
  "class_g = 'firefox-esr' && (window_type = 'utility' || window_type = 'popup_menu') && argb",
  "class_g = 'Firefox-esr' && (window_type = 'utility' || window_type = 'popup_menu') && argb",
  "class_g = 'Thunderbird' && (window_type = 'utility' || window_type = 'popup_menu') && argb",
  "class_g = 'Mozilla Thunderbird' && (window_type = 'utility' || window_type = 'popup_menu') && argb",
  "class_g ?= 'Xfce4-power-manager'",
  "_NET_WM_WINDOW_TYPE:a *= '_KDE_NET_WM_WINDOW_TYPE_OVERRIDE'",
  "class_g ~= 'xdg-desktop-portal-gnome' && _NET_FRAME_EXTENTS@:c && window_type = 'dialog'",
  "class_g ~= 'xdg-desktop-portal-gnome' && window_type = 'menu'",
  "_NET_FRAME_EXTENTS@:c && WM_WINDOW_ROLE@:s = 'Popup'",
  "class_g ?= 'xdg-desktop-portal' && (window_type = 'menu')"
];
shadow-ignore-shaped = true;

corner-radius = 8;

#################################
#
# Opacity
#
#################################

inactive-opacity = 0.85;
active-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;
#inactive-dim = 0.2;
#inactive-dim-fixed = true;
blur-background = false;
#blur-method = "kernel";
#blur-size = 20;
#blur-deviation = 25.0;
#blur-kern = "9x9gaussian"
blur-background-exclude = [ ];
opacity-exclude = [ ];


#################################
#
# Fading
#
#################################

fading = true;
#fade-delta = 30;
#fade-in-step = 0.03;
#fade-out-step = 0.03;
fade-in-step = 0.07;
fade-out-step = 0.07;
# no-fading-openclose = true;
# no-fading-destroyed-argb = true;
fade-exclude = [ ];


#################################
#
# OTHER CONFIG
#
#################################

log-level = "warn";
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
focus-exclude = [ "class_g = 'Cairo-clock'" ];
detect-transient = true;
detect-client-leader = true;
invert-color-include = [ ];
resize-damage = 2;


#################################
#
# Window type settings
#
#################################

wintypes:
{
  dock = { shadow = false; corner-radius = 0; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 1; corner-radius = 0; }
  dropdown_menu = { opacity = 1; corner-radius = 0; }
  menu = { shadow = false; blur-background = false; corner-radius = 0; };
  tooltip = { fade = true; shadow = false; };
};


