#!/bin/bash
#
#                ____            
#    ___  ____  / __ )____  _  __
#   / _ \/ __ \/ __  / __ \| |/_/
#  /  __/ / / / /_/ / /_/ />  <  
# \___/_/ /_/_____/\____/_/|_|  
#
# enBox Desktop Environment
# Set Display Resolution



## Automatically set's screen resolution for my common devices 

## Man Cave PC
if [[ "$HOSTNAME" == "out-back" ]]; then

	## Connected to  Apple Cinema Display 30"
	xrandr --newmode "2560x1600" 268.00 2560 2608 2640 2720 1600 1603 1609 1646
	xrandr --addmode DP-1 2560x1600
	xrandr --output DP-1 --primary --mode 2560x1600

## ThinkPad X1
elif [[ "$HOSTNAME" == "thebentobox"  ]]; then

	## Connected to Lenovo ThinkVision 27" displays
	if xrandr | grep -q "DP-1-5"; then
	    xrandr --output eDP-1 --off --output HDMI-1 --off --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --off --output DP-1-5 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP-1-6 --mode 2560x1440 --pos 2560x0 --rotate normal
	
	## Laptop display only
	else
	    xrandr --output eDP-1 --primary --mode 1920x1200
	fi

fi

exit 0